'\" t
.\"     Title: tlsrpt_set_nonblocking
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_set_nonblocking
.\"    Source: tlsrpt_set_nonblocking
.\"  Language: English
.\"
.TH "TLSRPT_SET_NONBLOCKING" "3" "2024-11-06" "tlsrpt_set_nonblocking" "tlsrpt_set_nonblocking"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_set_nonblocking \- restores the `sendto` call within `tlsrpt_finish_delivery_request` to its default non\-blocking behaviour
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
void tlsrpt_set_nonblocking()
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_set_nonblocking\fP function restores the \f[CR]sendto\fP call within \f[CR]tlsrpt_finish_delivery_request\fP to its default non\-blocking behaviour.
.SH "RETURN VALUE"
.sp
The tlsrpt_set_nonblocking function has no return value.
.SH "SEE ALSO"
.sp
\fBtlsrpt_set_blocking\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE