'\" t
.\"     Title: tlsrpt_errno_from_error_code
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_errno_from_error_code
.\"    Source: tlsrpt_errno_from_error_code
.\"  Language: English
.\"
.TH "TLSRPT_ERRNO_FROM_ERROR_CODE" "3" "2024-11-06" "tlsrpt_errno_from_error_code" "tlsrpt_errno_from_error_code"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_errno_from_error_code \- returns the `errno` part of an errorcode
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_errno_from_error_code(int errorcode)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_errno_from_error_code\fP function returns the \f[CR]errno\fP part of an errorcode.
In case of internal library errors from the TLSRPT_ERR_TLSRPT block the returned value will be a high number to avoid clashes with existing errno values.
I.e. \f[CR]TLSRPT_ERR_TLSRPT_NESTEDPOLICY\fP is 10731 instead of 10031 to avoid the errno part being decoded as \f[CR]EMLINK\fP.
.SH "RETURN VALUE"
.sp
The tlsrpt_errno_from_error_code function returns 0 on success and a combined error code on failure.
The combined error code can be analyzed with the \fItlsrpt_strerror\fP function.
.SH "SEE ALSO"
.sp
\fBtlsrpt_error_code_is_internal\fP(3), \fBtlsrpt_strerror\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE