'\" t
.\"     Title: tlsrpt_strerror
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_strerror
.\"    Source: tlsrpt_strerror
.\"  Language: English
.\"
.TH "TLSRPT_STRERROR" "3" "2024-11-06" "tlsrpt_strerror" "tlsrpt_strerror"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_strerror \- returns a static string describing the error
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
const char* tlsrpt_strerror(int errorcode)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_strerror\fP function returns a static string describing the error.
If the error is not an internal error (\f[CR]tlsrpt_error_code_is_internal\fP returns 0 in that case), the text describes the C library function that gave an error and for C library functions that get called from different places within the TLSRPT library, the calling function is mentioned in the description.
The actual error has to be retrieved from the C library via the \f[CR]strerror\fP function or its altrnatives.
The errno value to be passed into the \f[CR]strerror\fP function must be extracted from the error code via the \f[CR]tlsrpt_errno_from_error_code\fP function.
.SH "RETURN VALUE"
.sp
The tlsrpt_strerror function returns a static string describing the error.
.SH "SEE ALSO"
.sp
\fBtlsrpt_error_code_is_internal\fP(3), \fBtlsrpt_errno_from_error_code\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE