'\" t
.\"     Title: tlsrpt_add_mx_host_pattern
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_add_mx_host_pattern
.\"    Source: tlsrpt_add_mx_host_pattern
.\"  Language: English
.\"
.TH "TLSRPT_ADD_MX_HOST_PATTERN" "3" "2024-11-06" "tlsrpt_add_mx_host_pattern" "tlsrpt_add_mx_host_pattern"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_add_mx_host_pattern \- adds a MX host pattern to the current policy
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_add_mx_host_pattern(struct tlsrpt_dr_t* dr, const char* mx_host_pattern)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_add_mx_host_pattern\fP function adds a MX host pattern to the current policy.
Multiple MX host patterns can be added within a policy.
.SH "RETURN VALUE"
.sp
The tlsrpt_add_mx_host_pattern function returns 0 on success and a combined error code on failure.
The combined error code can be analyzed with the \fItlsrpt_strerror\fP function.
.SH "SEE ALSO"
.sp
\fBtlsrpt_strerror\fP(3), \fBtlsrpt_error_code_is_internal\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE