'\" t
.\"     Title: tlsrpt_get_socket
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_get_socket
.\"    Source: tlsrpt_get_socket
.\"  Language: English
.\"
.TH "TLSRPT_GET_SOCKET" "3" "2024-11-06" "tlsrpt_get_socket" "tlsrpt_get_socket"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_get_socket \- returns the socket file descriptor used within a `tlsrpt_connection_t`
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_get_socket(truct tlsrpt_connection_t* con)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_get_socket\fP function returns the socket file descriptor used within a \f[CR]tlsrpt_connection_t\fP.
This can be useful to set socket options.
.SH "RETURN VALUE"
.sp
The tlsrpt_get_socket function returns the socket file descriptor used within a tlsrpt_connection_t.
.SH "SEE ALSO"
.sp
\fBtlsrpt_strerror\fP(3), \fBtlsrpt_error_code_is_internal\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE