'\" t
.\"     Title: tlsrpt_error_code_is_internal
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_error_code_is_internal
.\"    Source: tlsrpt_error_code_is_internal
.\"  Language: English
.\"
.TH "TLSRPT_ERROR_CODE_IS_INTERNAL" "3" "2024-11-06" "tlsrpt_error_code_is_internal" "tlsrpt_error_code_is_internal"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_error_code_is_internal \- returns if the error code is internal to the TLSRPT library
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_error_code_is_internal(int errorcode)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_error_code_is_internal\fP function returns if the error code is internal to the TLSRPT library.
\f[CR]tlsrpt_error_code_is_internal\fP returns 1 if the error code describes an error internal to the TLSRPT library.
\f[CR]tlsrpt_error_code_is_internal\fP returns 0 if the error code is a composed error code combined of the C library function and the call site within the TLSRPT library and the errno value resulting from the failed call into the C library.
.SH "RETURN VALUE"
.sp
The tlsrpt_error_code_is_internal function returns if the error code is internal to the TLSRPT library.
.SH "SEE ALSO"
.sp
\fBtlsrpt_strerror\fP(3), \fBtlsrpt_errno_from_error_code\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE