'\" t
.\"     Title: tlsrpt_open
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_open
.\"    Source: tlsrpt_open
.\"  Language: English
.\"
.TH "TLSRPT_OPEN" "3" "2024-11-06" "tlsrpt_open" "tlsrpt_open"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_open \- `tlsrpt_open` allocates and initializes the `struct tlsrpt_connection_t` object
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_open(struct tlsrpt_connection_t** pcon, const char* socketname)
.SH "DESCRIPTION"
.sp
The function \f[CR]tlsrpt_open\fP allocates and initializes the \f[CR]struct tlsrpt_connection_t\fP object.
This function creates the socket and initializes the destination socket address of the TLSRPT collectd.
There is no actual connection internally, the socket is a connection\-less datagram socket.
.SH "RETURN VALUE"
.sp
The tlsrpt_open function returns 0 on success and a combined error code on failure.
The combined error code can be analyzed with the \fItlsrpt_strerror\fP function.
.SH "SEE ALSO"
.sp
\fBtlsrpt_close\fP(3), \fBtlsrpt_strerror\fP(3), \fBtlsrpt_error_code_is_internal\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE