'\" t
.\"     Title: tlsrpt_version
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_version
.\"    Source: tlsrpt_version
.\"  Language: English
.\"
.TH "TLSRPT_VERSION" "3" "2024-11-06" "tlsrpt_version" "tlsrpt_version"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_version \- returns a static string describing the version of libtlsrpt
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
const char* tlsrpt_version()
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_version\fP function returns a static string describing the version of libtlsrpt.
.sp
The string consists of major version, minor version, patch level and optionally a tag describing a pre\-release version.
.SH "RETURN VALUE"
.sp
The tlsrpt_version function returns a static string describing the version of libtlsrpt.
.SH "SEE ALSO"
.sp
\fBtlsrpt_version_check\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE