'\" t
.\"     Title: tlsrpt_version_check
.\"    Author: Boris Lohner
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2024-11-06
.\"    Manual: tlsrpt_version_check
.\"    Source: tlsrpt_version_check
.\"  Language: English
.\"
.TH "TLSRPT_VERSION_CHECK" "3" "2024-11-06" "tlsrpt_version_check" "tlsrpt_version_check"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
tlsrpt_version_check \- check whether the version of libtlsrpt is compatible with the calling program
.SH "SYNOPSIS"
.sp
#include <tlsrpt.h>
.sp
int tlsrpt_version_check(int major, int minor, int patch)
.SH "DESCRIPTION"
.sp
The \f[CR]tlsrpt_version_check\fP function checks whether the version of libtlsrpt is compatible with the calling program.
.sp
A program compiled with libtlsrpt version a.b.c can call \f[CR]tlsrpt_version_check(a, b, c)\fP to determine if the loaded library is compatible with the program.
.SH "RETURN VALUE"
.sp
The tlsrpt_version function returns 1 when the library is compatible with the calling program and 0 otherwise.
.SH "SEE ALSO"
.sp
\fBtlsrpt_version_check\fP(3)
.SH "AUTHOR(S)"
.sp
\fBBoris Lohner\fP
.RS 4
Author(s).
.RE